"""Run a generated Tcl script in headless VMD and read structured results back.

Every capability in :mod:`vmd_agent.vmdkit` is a Python function that *builds* a Tcl script
from validated values (never from caller-supplied Tcl), runs it here, and parses the
numbers VMD printed. The script body writes results with ``emit key v1 v2 ...``; each
becomes one row ``["v1", "v2", ...]`` under ``rows[key]``.

Safety: scripts are generated by this package only. Every path goes through
:func:`security.tcl_path`, every selection through :func:`security.tcl_selection`, every
number through ``int()``/``float()``, and every choice from a fixed list, so no
caller-controlled text can reach the Tcl interpreter as code.
"""
from __future__ import annotations

import os
import re
import tempfile
from typing import Dict, List, Optional, Sequence

from vmd_agent import security
from vmd_agent.environment import find_vmd
from vmd_agent.visual.render import _load_lines, _run_vmd_text

_PREAMBLE = """\
set ::vmdagent_out [open {RESULTS} w]
proc emit {args} { puts $::vmdagent_out [join $args { }]; flush $::vmdagent_out }
proc framerange {mol first last step} {
    set n [molinfo $mol get numframes]
    if {$last < 0 || $last >= $n} { set last [expr {$n - 1}] }
    set out {}
    for {set f $first} {$f <= $last} {incr f $step} { lappend out $f }
    return $out
}
"""


_STANDALONE_PREAMBLE = """\
# Results are printed as lines starting with RESULT. Run headless with:
#   vmd -dispdev text -eofexit -e THIS_FILE < /dev/null
proc emit {args} { puts "RESULT [join $args { }]" }
proc framerange {mol first last step} {
    set n [molinfo $mol get numframes]
    if {$last < 0 || $last >= $n} { set last [expr {$n - 1}] }
    set out {}
    for {set f $first} {$f <= $last} {incr f $step} { lappend out $f }
    return $out
}
"""

#: where to keep a copy of every script that is run, so any result can be reproduced in plain VMD
_CTX: Dict[str, Optional[str]] = {"dir": None, "label": "script", "last": None}
_COUNTER = [0]


def configure(script_dir: Optional[str], label: str = "script") -> None:
    """Keep a standalone copy of each script run from now on in ``script_dir`` (None to stop)."""
    _CTX.update(dir=script_dir, label=label, last=None)


def last_script() -> Optional[str]:
    """Path of the standalone script saved by the most recent run, if saving is on."""
    return _CTX["last"]


def _save(body: Sequence[str], vmd_path: str) -> None:
    if not _CTX["dir"]:
        return
    import time
    from vmd_agent import __version__
    os.makedirs(_CTX["dir"], exist_ok=True)
    _COUNTER[0] += 1
    path = os.path.join(_CTX["dir"], f"{time.strftime('%Y%m%d-%H%M%S')}_{_COUNTER[0]:03d}_{_CTX['label']}.tcl")
    with open(path, "w") as fh:
        fh.write(f"# vmd-agent {__version__}: the exact Tcl behind one `{_CTX['label']}` call (VMD at {vmd_path})\n")
        fh.write(_STANDALONE_PREAMBLE + "\n".join(body) + "\n")
    _CTX["last"] = path


def no_vmd() -> dict:
    return {"ok": False, "error": "VMD not found: this tool needs a real VMD. Install VMD 1.9.x and run "
                                  "`vmd-agent setup`, or set VMD_BIN."}


def sel(text: str) -> str:
    """A selection safe to put inside Tcl braces."""
    t = security.tcl_selection(text)
    if not t.strip():
        raise security.InvalidInput("empty selection")
    return t


def num(value, what: str = "value") -> float:
    try:
        v = float(value)
    except (TypeError, ValueError):
        raise security.InvalidInput(f"{what} must be a number")
    if v != v or v in (float("inf"), float("-inf")):
        raise security.InvalidInput(f"{what} must be finite")
    return v


def whole(value, what: str = "value") -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        raise security.InvalidInput(f"{what} must be an integer")


def choice(value: str, allowed: Sequence[str], what: str = "option") -> str:
    if value not in allowed:
        raise security.InvalidInput(f"{what} must be one of {', '.join(allowed)}")
    return value


def frame_args(first: int, last: int, step: int) -> tuple:
    first = 0 if first is None else whole(first, "first")         # a model passes null for "not given"
    step = 1 if step is None else whole(step, "step")
    last = -1 if last is None else whole(last, "last")            # None means "to the end"
    if first < 0 or step < 1:
        raise security.InvalidInput("first must be >= 0 and step >= 1")
    return first, last, step


def load(topology: str, trajectory: Optional[str] = None) -> List[str]:
    """Tcl lines that load the system and leave it as molecule ``top`` (VMD frame N == trajectory frame N).
    With a trajectory, it stops with a clear error if no frame was read (usually the atom counts differ)."""
    lines = _load_lines(topology, trajectory)
    if trajectory:
        lines.append('if {[molinfo top get numframes] < 1} { error "no frames were read from the trajectory: it '
                     'probably does not match the topology (different number of atoms)" }')
    return lines


def keep_inputs(outputs: Sequence[str], inputs: Sequence[Optional[str]]) -> None:
    """Refuse to write over a file the same call reads. A model that mixes up an input and an output name would
    otherwise destroy the user's data."""
    ins = {os.path.realpath(i) for i in inputs if i}
    for o in outputs:
        if o and os.path.realpath(o) in ins:
            raise security.InvalidInput(f"{os.path.basename(o)} is one of the input files; choose a different output "
                                        "name so the original is not overwritten")


def run(body: Sequence[str], vmd_path: Optional[str] = None, timeout: int = 900,
        cwd: Optional[str] = None) -> dict:
    """Run ``body`` (Tcl lines) in headless VMD. Returns ``{"ok", "rows", "log", "error"}``.

    ``rows`` maps each ``emit`` key to a list of token lists. ``ok`` is False if VMD is
    missing, a Tcl error occurred, or the script did not run to its end."""
    vmd = find_vmd(vmd_path)
    if not vmd:
        return no_vmd()
    _save(body, vmd)
    with tempfile.TemporaryDirectory(prefix="vmd_agent_kit_") as tmp:
        bodyfile = os.path.join(tmp, "body.tcl")
        main = os.path.join(tmp, "main.tcl")
        resfile = os.path.join(tmp, "results.txt")
        with open(bodyfile, "w") as fh:
            fh.write("\n".join(body) + "\n")
        with open(main, "w") as fh:
            fh.write(_PREAMBLE.replace("RESULTS", resfile))
            fh.write(f'if {{[catch {{source {{{bodyfile}}}}} err]}} {{ emit ERROR $err }}\n')
            fh.write("emit DONE\nquit\n")
        res = _run_vmd_text(vmd, main, timeout, cwd=cwd or tmp)
        try:
            with open(resfile) as fh:
                result_text = fh.read()
        except OSError:
            result_text = ""
    text = res.get("stdout", "") + "\n" + res.get("stderr", "")
    rows: Dict[str, List[List[str]]] = {}
    for line in result_text.splitlines():           # results go to a file, so VMD's chatter cannot truncate them
        parts = line.split()
        if parts:
            rows.setdefault(parts[0], []).append(parts[1:])
    out = {"rows": rows, "log": text[-1500:]}
    if res.get("returncode", 0) == -1:
        out.update(ok=False, error=res.get("stderr", "VMD timed out"))
    elif "ERROR" in rows:
        out.update(ok=False, error="VMD reported: " + " ".join(rows["ERROR"][0])[:400])
    elif "DONE" not in rows:
        out.update(ok=False, error="VMD stopped before the script finished: " + _last_message(text))
    else:
        out["ok"] = True
    return out


def _last_message(text: str) -> str:
    msgs = [ln for ln in text.splitlines() if re.search(r"error|can't|invalid|unable|cannot", ln, re.I)]
    return (msgs[-1] if msgs else text.strip().splitlines()[-1] if text.strip() else "no output")[:300]


def floats(tokens: Sequence[str]) -> List[float]:
    return [float(t) for t in tokens]
